#!/usr/bin/env zsh

builtin emulate -L zsh

builtin local -r func=zsh-no-ps2-test
if (( ${+functions[$func]} )); then
  builtin unfunction -- $func
fi
if functions[$func]=$PREBUFFER$BUFFER 2>/dev/null &&
   (( ${+functions[$func]} )); then
  builtin unfunction -- $func
  builtin local w
  builtin zstyle -s :zsh-no-ps2: accept-line w || w=accept-line
  if [[ -n $w ]]; then
    builtin zle -- $w
  fi
else
  LBUFFER+=$'\n'
fi
