#!/usr/bin/env zsh
#
# This autoloadable function can be used as the accept-line zle widget.
# If the current command is complete, the widget acts like the builtin
# accept-line. Otherwise, instead of going into PS2 like the builtin
# accept-line would do, it inserts \n at the cursor position.

builtin emulate -L zsh

builtin local -r func=zsh-no-ps2-test
if (( ${+functions[$func]} )); then
  builtin unfunction -- $func
fi
if functions[$func]=$PREBUFFER$BUFFER 2>/dev/null &&
   (( ${+functions[$func]} )); then
  builtin unfunction -- $func
  builtin local w
  builtin zstyle -s :zsh-no-ps2: accept-line w || w=accept-line
  if [[ -n $w ]]; then
    builtin zle -- $w
  fi
else
  LBUFFER+=$'\n'
fi
